### ISSUE TITLE
GenerateTemplates target in PresentationFramework.csproj is flaky

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/wpf#749]
On local builds, `GenerateTemplates` target in `PresentationFramework.csproj` sometimes generates empty `$(IntermediateOutputPath)ColumnDefinition.cs` and `$(IntermediateOutputPath)RowDefinition.cs` files. 

This leads to failures like the one reported in #748 

```
------ Build started: Project: PresentationFramework, Configuration: Debug Any CPU ------
System\Windows\Controls\Grid.cs(309,16,309,42): error CS0246: The type or namespace name 'ColumnDefinitionCollection' could not be found (are you missing a using directive or an assembly reference?)
System\Windows\Controls\Grid.cs(324,16,324,39): error CS0246: The type or namespace name 'RowDefinitionCollection' could not be found (are you missing a using directive or an assembly reference?)
System\Windows\Controls\Grid.cs(3347,22,3347,48): error CS0246: The type or namespace name 'ColumnDefinitionCollection' could not be found (are you missing a using directive or an assembly reference?)
System\Windows\Controls\Grid.cs(3348,22,3348,45): error CS0246: The type or namespace name 'RowDefinitionCollection' could not be found (are you missing a using directive or an assembly reference?)
System\Windows\Controls\Grid.cs(4151,21,4151,47): error CS0246: The type or namespace name 'ColumnDefinitionCollection' could not be found (are you missing a using directive or an assembly reference?)
System\Windows\Controls\Grid.cs(4152,21,4152,44): error CS0246: The type or namespace name 'RowDefinitionCollection' could not be found (are you missing a using directive or an assembly reference?)
Done building project "PresentationFramework.csproj" -- FAILED.
```
